version: "2"
linters:
  default: none 
  enable:
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        # A `-` preceding a linter name disables it.
        # Disable ST1000 to allow packages without comments
        - -ST1000
        # Disable ST1005 to allow error strings to start with uppercase letters
        - -ST1005
        # Disable ST1003 to allow underscores in variable names
        - -ST1003
        # Disable these 3 to allow comments on exported things to have the improper form
        - -ST1020
        - -ST1021
        - -ST1022

        # The following linters are disabled not because they SHOULD BE, but because
        # we haven't fix the issues they raise yet.
        # An enterprising contributor should feel free to delete these one by one and
        # fix the issues they flag.
        - -S1008
        - -S1017
        - -S1021
        - -S1023
        - -S1024
formatters:
  enable:
    - goimports
run:
  relative-path-mode: cfg
  go: '1.25.1'
output:
  formats:
    text:
      path: stderr
