version: "2"
linters:
  default: none 
  enable:
    - staticcheck
  settings:
    staticcheck:
      checks:
        - all
        # A `-` preceding a linter name disables it.
        # Disable ST1000 to allow packages without comments
        - -ST1000
        # Disable ST1005 to allow error strings to start with uppercase letters
        - -ST1005
        # Disable ST1003 to allow underscores in variable names
        - -ST1003
        # Disable these 3 to allow comments on exported things to have the improper form
        - -ST1020
        - -ST1021
        - -ST1022

formatters:
  enable:
    - goimports
run:
  relative-path-mode: cfg
  go: '1.26.2'
output:
  formats:
    text:
      path: stderr
