#!/bin/sh

# Generates the ssz encoding methods for eth2 types with fastssz
# Install sszgen with `go get github.com/ferranbt/fastssz/sszgen`
SSZGEN_CMD="go run github.com/ferranbt/fastssz/sszgen@v0.1.4"
find ./shared/types/eth2 -name "*_encoding.go" -exec sh -c 'head -1 {} | grep -q "Code generated by fastssz"' \; -exec rm {} \;
$SSZGEN_CMD --path ./shared/types/eth2/fork/deneb --include ./shared/types/eth2/generic
$SSZGEN_CMD --path ./shared/types/eth2/fork/electra --include ./shared/types/eth2/generic
$SSZGEN_CMD --path ./shared/types/eth2/generic --exclude-objs Uint256
