package config

func createIpfsStep(wiz *wizard, currentStep int, totalSteps int) *choiceWizardStep {

	helperText := "Would you like to enable the InterPlanetary File System (IPFS) node?\n\nThis feature will download and host the files generated by the Oracle DAO for all of Rocket Pool's rewards periods on the Peer-to-Peer IPFS network. These files contain each node's earned rewards and the proofs used to claim them.\n\nIf you enable this, your Smartnode will host all of those files so other Node Operators can retrieve them from more sources. This helps promote the overall decentralization and health of the network.\n\nFor more information on IPFS, please visit https://docs.ipfs.io/concepts/what-is-ipfs/"

	show := func(modal *choiceModalLayout) {
		wiz.md.setPage(modal.page)
		if wiz.md.Config.EnableIpfs.Value == false {
			modal.focus(0)
		} else {
			modal.focus(1)
		}
	}

	done := func(buttonIndex int, buttonLabel string) {
		if buttonIndex == 1 {
			wiz.md.Config.EnableIpfs.Value = true
		} else {
			wiz.md.Config.EnableIpfs.Value = false
		}
		wiz.finishedModal.show()
	}

	back := func() {
		if wiz.md.Config.ConsensusClientMode.Value == true {
			wiz.metricsModal.show()
		} else {
			wiz.metricsModal.show()
		}
	}

	return newChoiceStep(
		wiz,
		currentStep,
		totalSteps,
		helperText,
		[]string{"No", "Yes"},
		[]string{},
		76,
		"IPFS",
		DirectionalModalHorizontal,
		show,
		done,
		back,
		"step-ipfs",
	)

}
