// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: beacon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitteesResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index      uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Slot       uint64   `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Validators []uint64 `protobuf:"varint,3,rep,packed,name=validators,proto3" json:"validators,omitempty"`
}

func (x *CommitteesResponseData) Reset() {
	*x = CommitteesResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitteesResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteesResponseData) ProtoMessage() {}

func (x *CommitteesResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteesResponseData.ProtoReflect.Descriptor instead.
func (*CommitteesResponseData) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *CommitteesResponseData) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitteesResponseData) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitteesResponseData) GetValidators() []uint64 {
	if x != nil {
		return x.Validators
	}
	return nil
}

type CommitteesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data                []*CommitteesResponseData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	ExecutionOptimistic bool                      `protobuf:"varint,2,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	Finalized           bool                      `protobuf:"varint,3,opt,name=finalized,proto3" json:"finalized,omitempty"`
}

func (x *CommitteesResponse) Reset() {
	*x = CommitteesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitteesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteesResponse) ProtoMessage() {}

func (x *CommitteesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteesResponse.ProtoReflect.Descriptor instead.
func (*CommitteesResponse) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *CommitteesResponse) GetData() []*CommitteesResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommitteesResponse) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

func (x *CommitteesResponse) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

var File_beacon_proto protoreflect.FileDescriptor

var file_beacon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x62, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x74, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a,
	0x14, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6d,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beacon_proto_rawDescOnce sync.Once
	file_beacon_proto_rawDescData = file_beacon_proto_rawDesc
)

func file_beacon_proto_rawDescGZIP() []byte {
	file_beacon_proto_rawDescOnce.Do(func() {
		file_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(file_beacon_proto_rawDescData)
	})
	return file_beacon_proto_rawDescData
}

var file_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beacon_proto_goTypes = []interface{}{
	(*CommitteesResponseData)(nil), // 0: pb.CommitteesResponseData
	(*CommitteesResponse)(nil),     // 1: pb.CommitteesResponse
}
var file_beacon_proto_depIdxs = []int32{
	0, // 0: pb.CommitteesResponse.data:type_name -> pb.CommitteesResponseData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beacon_proto_init() }
func file_beacon_proto_init() {
	if File_beacon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beacon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitteesResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beacon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitteesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beacon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beacon_proto_goTypes,
		DependencyIndexes: file_beacon_proto_depIdxs,
		MessageInfos:      file_beacon_proto_msgTypes,
	}.Build()
	File_beacon_proto = out.File
	file_beacon_proto_rawDesc = nil
	file_beacon_proto_goTypes = nil
	file_beacon_proto_depIdxs = nil
}
