{
 "title": "Rocket Pool Dashboard v1.3.2",
 "description": "This is the standard dashboard for Rocket Pool node operators.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hardware Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validator Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Node Uptime",
   "type": "stat",
   "description": "A count of how long your Beacon Node has been running. If you don't restart it, this is about the same as your total system uptime.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"eth2\"}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "description": "The temperature of your CPU (you can set this to Tctl or Tdie, whichever you prefer to monitor).\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. See the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}"
    }
   ]
  },
  {
   "title": "Reboot Needed?",
   "type": "stat",
   "description": "This will turn red when your system needs to be rebooted because of security updates.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_reboot_required{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "description": "Tracks any updates that are available for your OS or for Rocket Pool but haven't been applied yet. When one of these numbers is higher than 0, it means you should update your system or Rocket Pool accordingly.\n\nSetting this up is Operating System specific, so it doesn't come ready out of the box; see the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(os_upgrades_pending{job=\"node\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "max(rocketpool_version_update{job=\"node\"})",
     "legendFormat": "Rocket Pool"
    }
   ]
  },
  {
   "title": "Swap Space Usage",
   "type": "gauge",
   "description": "How much of your total swap space you're currently using. If you have swap space enabled, you want this to be as low as possible - otherwise, your system is running out of free RAM.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node\"} - node_memory_SwapFree_bytes{job=\"node\"}) / node_memory_SwapTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "stat",
   "description": "Tracks the activity of all of your validators on the Beacon Chain. This is a cumulative count; it starts at 0 when your node first starts up, and then continuously increments as it goes.",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vc_signed_attestations_total{job=\"validator\", status=\"success\"}) OR # Lighthouse\nsum(vc_published_attestations_total{job=\"validator\"}) OR # Lodestar\nsum(beacon_attestations_sent_total{job=\"validator\"}) OR # Nimbus\nsum(validator_successful_attestations{job=\"validator\"}) OR # Prysm\nvalidator_duties_performed_total{job=\"validator\", type=\"attestation\", result=\"success\"} OR # Teku\non() vector(0)",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(vc_signed_beacon_blocks_total{job=\"validator\", status=\"success\"}) OR # Lighthouse\nsum(vc_block_published_total{job=\"validator\"}) OR # Lodestar\nsum(beacon_blocks_sent_total{job=\"validator\"}) OR # Nimbus\nsum(validator_successful_proposals{job=\"validator\"}) OR # Prysm\nvalidator_duties_performed_total{job=\"validator\", type=\"block\", result=\"success\"} OR # Teku\non() vector(0)",
     "legendFormat": "Proposals"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "timeseries",
   "description": "Tracks the activity of all of your validators on the Beacon Chain.",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(vc_signed_beacon_blocks_total{job=\"validator\", status=\"success\"}[$__rate_interval])) OR # Lighthouse\nsum(rate(vc_block_published_total{job=\"validator\"}[$__rate_interval])) OR # Lodestar\nsum(rate(beacon_blocks_sent_total{job=\"validator\"}[$__rate_interval])) OR # Nimbus\nsum(rate(validator_successful_proposals{job=\"validator\"}[$__rate_interval])) OR # Prysm\nrate(validator_duties_performed{job=\"validator\", type=\"block\", result=\"success\"}[$__rate_interval]) OR # Teku\non() vector(0)) * 45",
     "legendFormat": "Proposal"
    },
    {
     "expr": "(sum(rate(vc_signed_attestations_total{job=\"validator\", status=\"success\"}[$__rate_interval])) OR # Lighthouse\nsum(rate(vc_published_attestations_total{job=\"validator\"}[$__rate_interval])) OR # Lodestar\nsum(rate(beacon_attestations_sent_total{job=\"validator\"}[$__rate_interval])) OR # Nimbus\nsum(rate(validator_successful_attestations{job=\"validator\"}[$__rate_interval])) OR # Prysm\nrate(validator_duties_performed{job=\"validator\", type=\"attestation\", result=\"success\"}[$__rate_interval]) OR # Teku\non() vector(0)) * 45",
     "legendFormat": "Attestation"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "The CPU usage of your Execution Client and Beacon Node + Validator Client pair, as well as your system total (with respect to all cores on your CPU).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_cpu_procload{job=\"geth\"} / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))) OR # Geth\nirate(process_cpu_seconds_total{job=\"eth1\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) OR # Besu, Nethermind\nirate(reth_process_cpu_seconds_total{job=\"eth1\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) # Reth",
     "legendFormat": "EC"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"eth2\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval]))) or vector(0))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "(1 - avg (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "System Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "The amount of RAM that your Execution Client, Beacon Node and Validator Client combo, and your whole system are using.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"geth\"} OR # Geth\nprocess_resident_memory_bytes{job=\"eth1\"} OR # Besu\nprocess_working_set_bytes{job=\"eth1\"} OR # Nethermind\nreth_process_resident_memory_bytes{job=\"eth1\"} # Reth",
     "legendFormat": "EC"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"eth2\"}) + (sum(process_resident_memory_bytes{job=\"validator\"}) or vector(0))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "System Total"
    }
   ]
  },
  {
   "title": "Upcoming Proposals",
   "type": "stat",
   "description": "The number of block proposals you have coming up in the next few minutes. If you were planning on taking your node down for maintenance, you should wait until after the proposals because they're worth a lot of ETH!",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_beacon_upcoming_proposals"
    }
   ]
  },
  {
   "title": "Sync Committees",
   "type": "stat",
   "description": "The number of [sync committees](https://github.com/ethereum/annotated-spec/blob/master/altair/sync-protocol.md#introduction) that you're about to be a part of, and that you're currently a part of.\n\nIf you were planning on doing maintenance to your node, **you should wait until the sync committee is over**. Not only are they worth an **extremely** large amount of ETH, but if you miss attestations during a sync committee, you **lose an extremely large amount of ETH** instead!\n\nYou should be online as long as possible while you are in a sync committee.",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_beacon_upcoming_sync_committee",
     "legendFormat": "Upcoming"
    },
    {
     "expr": "rocketpool_beacon_active_sync_committee",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Attestation Accuracy",
   "type": "timeseries",
   "description": "This chart shows the overall performance of your total attestations on the Beacon Chain, broken down by the individual attestation components - correct head, correct source, and correct target. If any of these are below 100%, you lost some rewards for submitting a late, partially incorrect, or fully incorrect attestation. For a detailed explanation of each component, take a look at Ben Edgington's explainer: https://eth2book.info/bellatrix/annotated-spec/\n\nThis is updated once per epoch, once your Beacon Node can see how well your node did during the previous epoch.\n\nNOTE: **Lighthouse** and **Teku** currently do not provide source correctness information, only head and target.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(validator_monitor_prev_epoch_on_chain_target_attester_hit{job=\"eth2\", validator=\"total\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_target_attester_hit{job=\"eth2\", validator=\"total\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_target_attester_miss{job=\"eth2\", validator=\"total\"}[$__rate_interval]))) OR # Lighthouse\n(irate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total{job=\"eth2\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total{job=\"eth2\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total{job=\"eth2\"}[$__rate_interval]))) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_target{job=\"validator\"}) / count(validator_correctly_voted_target{job=\"validator\"})) OR # Prysm\n(validator_performance_correct_target_count{job=\"eth2\"} / validator_performance_expected_attestations{job=\"eth2\"}) # Teku",
     "legendFormat": "Target"
    },
    {
     "expr": "irate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total{job=\"eth2\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total{job=\"eth2\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total{job=\"eth2\"}[$__rate_interval])) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_source{job=\"validator\"}) / count(validator_correctly_voted_source{job=\"validator\"})) # Prysm",
     "legendFormat": "Source"
    },
    {
     "expr": "irate(validator_monitor_prev_epoch_on_chain_head_attester_hit{job=\"eth2\", validator=\"total\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_head_attester_hit{job=\"eth2\", validator=\"total\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_head_attester_miss{job=\"eth2\", validator=\"total\"}[$__rate_interval])) OR # Lighthouse\nirate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total{job=\"eth2\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total{job=\"eth2\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total{job=\"eth2\"}[$__rate_interval])) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_head{job=\"validator\"}) / count(validator_correctly_voted_head{job=\"validator\"})) OR # Prysm\n(validator_performance_correct_head_block_count{job=\"eth2\"} / validator_performance_expected_attestations{job=\"eth2\"}) # Teku",
     "legendFormat": "Head"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Tracks the amount of CPU consumption for the Execution Client, the Beacon Node, and the total system. 100% means all of your CPU core are being used at their full capacity. The orange line indicates how much CPU a single core can provide in your system.\n\n**Note:** The EC's usage is stacked *on top of* the BN+VC, so it shows the aggregated amount of EC + BN + VC.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"eth2\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"validator\"}[$__rate_interval]))) or vector(0))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "(system_cpu_procload{job=\"geth\"} / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))) OR # Geth\nirate(process_cpu_seconds_total{job=\"eth1\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) OR # Besu, Nethermind\nirate(reth_process_cpu_seconds_total{job=\"eth1\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) # Reth",
     "legendFormat": "EC (Stacked)"
    },
    {
     "expr": "100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "Single Core Cap"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Tracks the total amount of RAM usage by the eth2 client and the entire system, versus how much is available.\n\n**Note:** The EC's usage is stacked *on top of* the BN+VC, so it shows the aggregated amount of EC + BN + VC.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"eth2\"}) + (sum(process_resident_memory_bytes{job=\"validator\"}) or vector(0))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "system_memory_used{job=\"geth\"} OR # Geth\nprocess_resident_memory_bytes{job=\"eth1\"} OR # Besu\nprocess_working_set_bytes{job=\"eth1\"} OR # Nethermind\nreth_process_resident_memory_bytes{job=\"eth1\"} # Reth",
     "legendFormat": "EC (Stacked)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Next Attestation",
   "type": "stat",
   "description": "This tells you when your next attestation duty will arrive. Use it to find an optimal time to take your clients down for maintenance so you're back up and running before it hits.\n\n- NOTE: **Lodestar** and **Teku** do not provide this information.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((min(vc_attestation_duty_slot{job=\"validator\"}) - scalar(beacon_head_slot{job=\"eth2\"})) * 12) OR # Lighthouse\nmax(next_action_wait{job=\"eth2\"} OR # Nimbus\n(min((validator_next_attestation_slot{job=\"validator\"} - scalar(beacon_slot{job=\"eth2\"})) > 0 - 1) * 12) OR # Prysm\non() vector(0))"
    }
   ]
  },
  {
   "title": "Your Minipools",
   "type": "stat",
   "description": "How many minipools you currently have running on your node.",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_active_minipool_count"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "EC Peers",
   "type": "gauge",
   "description": "How many peers your EC is currently connected to.",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"geth\"} OR # Geth\nethereum_peer_count{job=\"eth1\"} OR # Nethermind, Besu\nreth_network_connected_peers{job=\"eth1\"} # Reth"
    }
   ]
  },
  {
   "title": "BN Peers",
   "type": "gauge",
   "description": "How many peers your Beacon Node is currently connected to on the Beacon Chain.",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sync_peers_per_status{job=\"eth2\", sync_status=~\"Synced|Advanced\"}) OR # Lighthouse\nlodestar_peers_sync_count{job=\"eth2\"} OR # Lodestar\nnbc_peers{job=\"eth2\"} OR # Nimbus\np2p_peer_count{job=\"eth2\", state=\"Connected\"} OR # Prysm\nbeacon_peer_count{job=\"eth2\"} # Teku"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "How many peers Execution Client and Beacon Node are currently connected to for blockchain traffic.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sync_peers_per_status{job=\"eth2\", sync_status=~\"Synced|Advanced\"}) OR # Lighthouse\nlodestar_peers_sync_count{job=\"eth2\"} OR # Lodestar\nnbc_peers{job=\"eth2\"} OR # Nimbus\np2p_peer_count{job=\"eth2\", state=\"Connected\"} OR # Prysm\nbeacon_peer_count{job=\"eth2\"} # Teku",
     "legendFormat": "BN"
    },
    {
     "expr": "p2p_peers{job=\"geth\"} OR # Geth\nethereum_peer_count{job=\"eth1\"} OR # Nethermind, Besu\nreth_network_connected_peers{job=\"eth1\"} # Reth",
     "legendFormat": "EC"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "timeseries",
   "description": "This tracks how long it takes between one of your processes trying to read from / write to your SSD, and when that operation is actually performed. Think of this like \"how long SSD reads and writes have to wait in a queue before completing\". The longer this time, the longer it takes for your node to perform its Beacon Chain duties.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "The disk space used by your primary (Operating System) hard drive. Change the `device` option in this query to be your machine's hard drive.\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}",
     "legendFormat": "OS"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", device=\"\"} - node_filesystem_avail_bytes{job=\"node\", device=\"\"}) / node_filesystem_size_bytes{job=\"node\", device=\"\"}",
     "legendFormat": "Disk 2"
    }
   ]
  },
  {
   "title": "Disk Temp",
   "type": "stat",
   "description": "The temperature of your SSD.\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. See the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}",
     "legendFormat": "OS"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}",
     "legendFormat": "Disk 2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Chain Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SSD Latency",
   "type": "timeseries",
   "description": "The average read/write latency of your SSD. The lower it is, the faster your machine can process and respond to Beacon Chain activities like attesting. Change the `device` setting in the queries to be the SSD you want to track (typically the one with your chain data on it).\n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "OS Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "OS Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Disk 2 Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Disk 2 Read"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "A chart showing the network I/O used by your main network adapter over time. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Total Net I/O",
   "type": "stat",
   "description": "The total network I/O that has gone through your main network adapter. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nSee the documentation at https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Tx"
    },
    {
     "expr": "node_network_receive_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Beacon Balance",
   "type": "stat",
   "description": "The total ETH balance of all of your Rocket Pool validators on the Beacon Chain. This includes both ETH belonging to you and ETH belonging to the pool stakers you used to make your minipools.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_balance{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Minipool Balance (EL)",
   "type": "stat",
   "description": "This is how much ETH is currently available for distribution in all of your minipool contracts (on the execution layer). Note that if any of them have a refund, this shows the total balance **minus** that refund amount - in other words, it shows whatever's left over after your refund.",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_minipool_balance{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Other ETH Rewards",
   "type": "stat",
   "description": "A collection of other ETH rewards you can claim (or have claimed).\n\n- **Unclaimed ETH (SP)**: ETH you've earned from the Smoothing Pool that you haven't claimed yet.\n- **Claimed ETH (SP)**: ETH from the Smoothing Pool you've already claimed in the past.\n- **Total Refund**: ETH that belongs to you from special operations like bond reduction or solo staker migration. When you claim this, it goes directly to you - it isn't split with the pool stakers.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_unclaimed_eth_rewards{job=\"rocketpool\"}",
     "legendFormat": "Unclaimed ETH (SP)"
    },
    {
     "expr": "rocketpool_node_claimed_eth_rewards{job=\"rocketpool\"}",
     "legendFormat": "Claimed ETH (SP)"
    },
    {
     "expr": "rocketpool_node_refund_balance{job=\"rocketpool\"}",
     "legendFormat": "Total Refund"
    }
   ]
  },
  {
   "title": "Your Beacon Chain Share",
   "type": "stat",
   "description": "This is how much ETH you will receive if you exit all of your validators on the Beacon Chain; it's your share of the total balance for each Rocket Pool minipool.",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_share{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Your Minipool (EL) Share",
   "type": "stat",
   "description": "The total amount of ETH that belongs to you across the EL balances of all of your minipool contracts (minus any refunds you may have waiting).",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_minipool_share{job=\"rocketpool\"}",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Rocket Pool Network Stats (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total ETH Locked",
   "type": "stat",
   "description": "The total amount of ETH locked on the Rocket Pool network, including staked RPL (but not including Beacon Chain rewards).",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{job=\"rocketpool\"} + rocketpool_demand_total_minipool_capacity{job=\"rocketpool\"} + rocketpool_supply_active_minipools{job=\"rocketpool\"} * 32 + rocketpool_rpl_total_value_staked{job=\"rocketpool\"} * rocketpool_rpl_rpl_price{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Total RPL Staked",
   "type": "stat",
   "description": "The total amount of RPL staked across all node operators in the Rocket Pool network.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_value_staked{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Total Effective RPL Staked",
   "type": "stat",
   "description": "The total *effective* RPL stake across all node operators on the Rocket Pool network. This accounts for the 150% collateral cap per minipool. If this number is lower than the Total RPL Staked, then some node operators have gone above 150%.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_effective_staked{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Smoothing Pool Balance",
   "type": "stat",
   "description": "The current balance of the Smoothing Pool. This is what will get distributed to each node operator opted into the Smoothing Pool at the end of each rewards interval.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_smoothing_pool_eth_balance"
    }
   ]
  },
  {
   "title": "RPL Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "The time of the next RPL rewards checkpoint. If you have an effective RPL stake greater than zero, you should receive rewards here (unless it's your first checkpoint, in which case you'll need to wait a bit longer).",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "This tracks how long you have until the next RPL rewards checkpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "rETH Price (ETH / rETH)",
   "type": "stat",
   "description": "The amount of ETH that 1 rETH is worth.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_reth_exchange_rate{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "RPL Price (ETH / RPL)",
   "type": "stat",
   "description": "The amount of ETH that 1 RPL is worth, as reported by the Oracle DAO. This updates somewhat infrequently, so it's expected if it falls out of sync with other price watchers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_rpl_price{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Staking Pool Balance",
   "type": "gauge",
   "description": "The amount of ETH currently in the staking pool, waiting to be used by node operators to create new minipools.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Minipools in Queue",
   "type": "stat",
   "description": "The number of minipools that are currently in the queue, waiting for ETH to be assigned to them from the staking pool.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_queue_length{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "RPL Staked",
   "type": "stat",
   "description": "This shows various levels of RPL stake you have:\n\n- **Total**: the total amount of RPL you have staked.\n- **Effective**: the amount of your staked RPL that is being put to use, accounting for the 10% borrowed minimum and 150% bonded maximum limits.\n- **Rewardable**: the effective amount of RPL that is eligible for earning RPL rewards at the end of each rewards period. This is based on the status of your validators on the Beacon Chain; validators that haven't been activated yet or validators that have been exited are not eligible for rewards.\n\n**Note**: this takes any *pending bond reductions* you may have into account.",
   "gridPos": { "h": 13, "w": 3, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_total_staked_rpl{job=\"rocketpool\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "rocketpool_node_effective_staked_rpl{job=\"rocketpool\"}",
     "legendFormat": "Effective"
    },
    {
     "expr": "rocketpool_node_rewardable_staked_rpl{job=\"rocketpool\"}",
     "legendFormat": "Rewardable"
    }
   ]
  },
  {
   "title": "RPL Collateral",
   "type": "gauge",
   "description": "Your total staked RPL collateral levels. This shows your collateral relative to the amount of ETH you have *borrowed* from the staking pool to complete your validators, and the amount of ETH you have *bonded* with your own funds.\n\nIf you fall below 10% of the *borrowed* ETH, you won't be able to claim your rewards at the next checkpoint until you get back to 10%.\n\nIf you go over 150% of the *bonded* ETH, you'll only be rewarded for the first 150% of your stake.",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_borrowed_collateral_ratio{job=\"rocketpool\"}",
     "legendFormat": "Borrowed"
    },
    {
     "expr": "rocketpool_node_bonded_collateral_ratio{job=\"rocketpool\"}",
     "legendFormat": "Bonded"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "The total number of nodes that have registered on the Rocket Pool network.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_node_count{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Minipools by Status",
   "type": "piechart",
   "description": "A breakdown of the counts of each minipool on the Rocket Pool network by status:\n\n- **Initialized**: waiting for a deposit still\n- **Prelaunch:** deposits are done, waiting to be staked by the node operator's `rocketpool_node` container \n- **Staking:** deposited, validator created, and active (or pending) on the Beacon Chain\n- **Dissolved:** staking failed, funds returned to the node operator and staking pool\n- **Withdrawable:** exited from the Beacon Chain, waiting for rewards to be withdrawn to the minipool\n- **Finalized:** exited, withdrawn from, and essentially closed (inactive)",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_minipool_count{job=\"rocketpool\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Staking Pool ETH Used",
   "type": "gauge",
   "description": "The relative amount of ETH that was deposited into the staking pool by rETH stakers, which was then used by node operators to create new minipools with validators on the Beacon Chain. The closer this number is to 100%, the more efficiently the Rocket Pool network is operating and the faster rETH's price grows.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_utilization_rate{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "ETH Capacity of Queue",
   "type": "stat",
   "description": "The total amount of ETH needed to be added to the staking pool in order to clear the minipool queue completely.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_total_minipool_capacity"
    }
   ]
  },
  {
   "title": "Active Minipools",
   "type": "stat",
   "description": "The total number of Rocket Pool minipools (validators) that are active (not exited and withdrawn from the Beacon Chain).",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_active_minipools{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "Approx. Rewards from Next Checkpoint",
   "type": "stat",
   "description": "The approximate amount of RPL you'll receive at the next checkpoint, based on your current rewardable stake and how much RPL is staked on the entire network.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_expected_rpl_rewards{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "title": "RPL Rewards",
   "type": "stat",
   "description": "The amount of RPL you've claimed over the life of your node, and the amount you still have yet to claim.",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_unclaimed_rewards{job=\"rocketpool\"}",
     "legendFormat": "Unclaimed"
    },
    {
     "expr": "rocketpool_node_cumulative_rpl_rewards{job=\"rocketpool\"}",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Governance (Updates Every 6 Hours)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Proposals",
   "type": "stat",
   "description": "The number of active proposals you or your delegate have voted on.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_votes_active",
     "legendFormat": "Voted"
    },
    {
     "expr": "rocketpool_snapshot_proposals_active - rocketpool_snapshot_votes_active",
     "legendFormat": "Missing votes"
    }
   ]
  },
  {
   "title": "Closed Proposals",
   "type": "stat",
   "description": "Shows the number of closed votes you or your delegate has voted or missed.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_votes_closed",
     "legendFormat": "Voted"
    },
    {
     "expr": "rocketpool_snapshot_proposals_closed - rocketpool_snapshot_votes_closed",
     "legendFormat": "Missed votes"
    }
   ]
  },
  {
   "title": "Node Voting Power",
   "type": "stat",
   "description": "The node voting power on Snapshot.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rocketpool_snapshot_node_vp " }
   ]
  },
  {
   "title": "Delegate Voting Power",
   "type": "stat",
   "description": "The voting power of the delegate you have chosen.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_delegate_vp "
    }
   ]
  },
  {
   "title": "Your RPL APR for the Next Checkpoint",
   "type": "stat",
   "description": "The approximate APR for your RPL stake, based on the rewards you will receive at the next checkpoint.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_rpl_apr{job=\"rocketpool\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Wallet Balances",
   "type": "table",
   "description": "The balances of your node wallet (only tracks Rocket Pool tokens). Keep an eye on how much ETH you have; if it falls too low, your node won't be able to pay for gas during automatic RPL reward claims or other transactions.",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 48 },
   "targets": [
    {
     "expr": "rocketpool_node_balance{job=\"rocketpool\"}",
     "legendFormat": "{{Token}}"
    }
   ]
  }
 ]
}