package wallet

import (
	"context"

	"github.com/urfave/cli/v3"

	cliutils "github.com/rocket-pool/smartnode/shared/utils/cli"
	"github.com/rocket-pool/smartnode/shared/utils/cli/color"
)

// Register commands
func RegisterCommands(app *cli.Command, name string, aliases []string) {
	app.Commands = append(app.Commands, &cli.Command{
		Name:    name,
		Aliases: aliases,
		Usage:   "Manage the node wallet",
		Commands: []*cli.Command{

			{
				Name:      "status",
				Aliases:   []string{"s"},
				Usage:     "Get the node wallet status",
				UsageText: "rocketpool wallet status",
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Run
					return getStatus()

				},
			},

			{
				Name:      "init",
				Aliases:   []string{"i"},
				Usage:     "Initialize the node wallet",
				UsageText: "rocketpool wallet init [options]",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:    "password",
						Aliases: []string{"p"},
						Usage:   "The password to secure the wallet with (if not already set)",
					},
					&cli.BoolFlag{
						Name:    "confirm-mnemonic",
						Aliases: []string{"c"},
						Usage:   "Automatically confirm the mnemonic phrase",
					},
					&cli.StringFlag{
						Name:    "derivation-path",
						Aliases: []string{"d"},
						Usage:   "Specify the derivation path for the wallet.\nOmit this flag (or leave it blank) for the default of \"m/44'/60'/0'/0/%d\" (where %d is the index).\nSet this to \"ledgerLive\" to use Ledger Live's path of \"m/44'/60'/%d/0/0\".\nSet this to \"mew\" to use MyEtherWallet's path of \"m/44'/60'/0'/%d\".\nFor custom paths, simply enter them here.",
					},
				},
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Validate flags
					if c.String("password") != "" {
						if _, err := cliutils.ValidateNodePassword("password", c.String("password")); err != nil {
							return err
						}
					}

					// Run
					return initWallet(c.String("password"), c.Bool("confirm-mnemonic"), c.String("derivation-path"), c.Root().Bool("secure-session"))

				},
			},

			{
				Name:      "recover",
				Aliases:   []string{"r"},
				Usage:     "Recover a node wallet from a mnemonic phrase",
				UsageText: "rocketpool wallet recover [options]",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:    "password",
						Aliases: []string{"p"},
						Usage:   "The password to secure the wallet with (if not already set)",
					},
					&cli.StringFlag{
						Name:    "mnemonic",
						Aliases: []string{"m"},
						Usage:   "The mnemonic phrase to recover the wallet from",
					},
					&cli.BoolFlag{
						Name:    "skip-validator-key-recovery",
						Aliases: []string{"k"},
						Usage:   "Recover the node wallet, but do not regenerate its validator keys",
					},
					&cli.StringFlag{
						Name:    "derivation-path",
						Aliases: []string{"d"},
						Usage:   "Specify the derivation path for the wallet.\nOmit this flag (or leave it blank) for the default of \"m/44'/60'/0'/0/%d\" (where %d is the index).\nSet this to \"ledgerLive\" to use Ledger Live's path of \"m/44'/60'/%d/0/0\".\nSet this to \"mew\" to use MyEtherWallet's path of \"m/44'/60'/0'/%d\".\nFor custom paths, simply enter them here.",
					},
					&cli.Uint64Flag{
						Name:    "wallet-index",
						Aliases: []string{"i"},
						Usage:   "Specify the index to use with the derivation path when recovering your wallet",
						Value:   0,
					},
					&cli.StringFlag{
						Name:    "address",
						Aliases: []string{"a"},
						Usage:   "If you are recovering a wallet that was not generated by the Smart Node and don't know the derivation path or index of it, enter the address here. the Smart Node will search through its library of paths and indices to try to find it.",
					},
				},
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Validate flags
					if c.String("password") != "" {
						if _, err := cliutils.ValidateNodePassword("password", c.String("password")); err != nil {
							return err
						}
					}
					if c.String("mnemonic") != "" {
						if _, err := cliutils.ValidateWalletMnemonic("mnemonic", c.String("mnemonic")); err != nil {
							return err
						}
					}

					// Run
					return recoverWallet(
						c.String("password"),
						c.String("mnemonic"),
						c.String("address"),
						c.Bool("skip-validator-key-recovery"),
						c.String("derivation-path"),
						c.Uint("wallet-index"),
					)

				},
			},

			{
				Name:      "rebuild",
				Aliases:   []string{"b"},
				Usage:     "Rebuild validator keystores from derived keys",
				UsageText: "rocketpool wallet rebuild",
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Run
					return rebuildWallet()

				},
			},

			{
				Name:      "test-recovery",
				Aliases:   []string{"t"},
				Usage:     "Test recovering a node wallet without actually generating any of the node wallet or validator key files to ensure the process works as expected",
				UsageText: "rocketpool wallet test-recovery [options]",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:    "mnemonic",
						Aliases: []string{"m"},
						Usage:   "The mnemonic phrase to recover the wallet from",
					},
					&cli.BoolFlag{
						Name:    "skip-validator-key-recovery",
						Aliases: []string{"k"},
						Usage:   "Recover the node wallet, but do not regenerate its validator keys",
					},
					&cli.StringFlag{
						Name:    "derivation-path",
						Aliases: []string{"d"},
						Usage:   "Specify the derivation path for the wallet.\nOmit this flag (or leave it blank) for the default of \"m/44'/60'/0'/0/%d\" (where %d is the index).\nSet this to \"ledgerLive\" to use Ledger Live's path of \"m/44'/60'/%d/0/0\".\nSet this to \"mew\" to use MyEtherWallet's path of \"m/44'/60'/0'/%d\".\nFor custom paths, simply enter them here.",
					},
					&cli.Uint64Flag{
						Name:    "wallet-index",
						Aliases: []string{"i"},
						Usage:   "Specify the index to use with the derivation path when recovering your wallet",
						Value:   0,
					},
					&cli.StringFlag{
						Name:    "address",
						Aliases: []string{"a"},
						Usage:   "If you are recovering a wallet that was not generated by the Smart Node and don't know the derivation path or index of it, enter the address here. the Smart Node will search through its library of paths and indices to try to find it.",
					},
				},
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Validate flags
					if c.String("mnemonic") != "" {
						if _, err := cliutils.ValidateWalletMnemonic("mnemonic", c.String("mnemonic")); err != nil {
							return err
						}
					}

					// Run
					return testRecovery(
						c.String("mnemonic"),
						c.String("address"),
						c.Bool("skip-validator-key-recovery"),
						c.String("derivation-path"),
						c.Uint("wallet-index"),
					)

				},
			},

			{
				Name:      "export",
				Aliases:   []string{"e"},
				Usage:     "Export the node wallet in JSON format",
				UsageText: "rocketpool wallet export",
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Run
					return exportWallet(c.Root().Bool("secure-session"))

				},
			},
			{
				Name:      "set-ens-name",
				Aliases:   []string{"ens"},
				Usage:     "Set a name to the node wallet's ENS reverse record",
				UsageText: "rocketpool wallet set-ens-name name",
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 1); err != nil {
						return err
					}

					// Run
					return setEnsName(c.Args().Get(0), c.Bool("yes"))

				},
			},

			{
				Name:      "purge",
				Usage:     color.Red("Deletes your node wallet, your validator keys, and restarts your Validator Client while preserving your chain data. WARNING: Only use this if you want to stop validating with this machine!"),
				UsageText: "rocketpool wallet purge",
				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Run
					return purge(cliutils.Parent(c).StringSlice("compose-file"))

				},
			},

			{
				Name:      "masquerade",
				Aliases:   []string{"m"},
				Usage:     "Change your node's effective address to a different one. Your node will not be able to submit transactions or sign messages since you don't have the corresponding wallet's private key.",
				UsageText: "rocketpool wallet m [options]",
				Flags: []cli.Flag{
					&cli.BoolFlag{
						Name:    "yes",
						Aliases: []string{"y"},
						Usage:   "Automatically confirm all interactive questions",
					},
					&cli.StringFlag{
						Name:    "address",
						Aliases: []string{"a"},
						Usage:   "Specify an address you'd like you masquerade as",
					},
				},

				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {

						return err
					}

					// Run
					return masquerade(c.String("address"), c.Bool("yes"))

				},
			},

			{
				Name:      "end-masquerade",
				Aliases:   []string{"em"},
				Usage:     "End a masquerade, restoring your node's effective address back to your wallet address if one is loaded.",
				UsageText: "rocketpool wallet end-masquerade [options]",
				Flags: []cli.Flag{
					&cli.BoolFlag{
						Name:    "yes",
						Aliases: []string{"y"},
						Usage:   "Automatically confirm all interactive questions",
					},
				},

				Action: func(ctx context.Context, c *cli.Command) error {

					// Validate args
					if err := cliutils.ValidateArgCount(c, 0); err != nil {
						return err
					}

					// Run
					return endMasquerade(c.Bool("yes"))

				},
			},
		},
	})
}
