// Code generated by fastssz. DO NOT EDIT.
// Hash: 0ce1692720cc8390d3c6d00634871beb54e72c70921bd837f50da392481fa167
// Version: 0.1.3
package gloas

import (
	ssz "github.com/ferranbt/fastssz"
	"github.com/rocket-pool/smartnode/shared/types/eth2/generic"
)

// MarshalSSZ ssz marshals the Builder object
func (b *Builder) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the Builder object to a target array
func (b *Builder) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Pubkey'
	if size := len(b.Pubkey); size != 48 {
		err = ssz.ErrBytesLengthFn("Builder.Pubkey", size, 48)
		return
	}
	dst = append(dst, b.Pubkey...)

	// Field (1) 'Version'
	dst = ssz.MarshalUint8(dst, b.Version)

	// Field (2) 'ExecutionAddress'
	dst = append(dst, b.ExecutionAddress[:]...)

	// Field (3) 'Balance'
	dst = ssz.MarshalUint64(dst, b.Balance)

	// Field (4) 'DepositEpoch'
	dst = ssz.MarshalUint64(dst, b.DepositEpoch)

	// Field (5) 'WithdrawableEpoch'
	dst = ssz.MarshalUint64(dst, b.WithdrawableEpoch)

	return
}

// UnmarshalSSZ ssz unmarshals the Builder object
func (b *Builder) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 93 {
		return ssz.ErrSize
	}

	// Field (0) 'Pubkey'
	if cap(b.Pubkey) == 0 {
		b.Pubkey = make([]byte, 0, len(buf[0:48]))
	}
	b.Pubkey = append(b.Pubkey, buf[0:48]...)

	// Field (1) 'Version'
	b.Version = ssz.UnmarshallUint8(buf[48:49])

	// Field (2) 'ExecutionAddress'
	copy(b.ExecutionAddress[:], buf[49:69])

	// Field (3) 'Balance'
	b.Balance = ssz.UnmarshallUint64(buf[69:77])

	// Field (4) 'DepositEpoch'
	b.DepositEpoch = ssz.UnmarshallUint64(buf[77:85])

	// Field (5) 'WithdrawableEpoch'
	b.WithdrawableEpoch = ssz.UnmarshallUint64(buf[85:93])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Builder object
func (b *Builder) SizeSSZ() (size int) {
	size = 93
	return
}

// HashTreeRoot ssz hashes the Builder object
func (b *Builder) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the Builder object with a hasher
func (b *Builder) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Pubkey'
	if size := len(b.Pubkey); size != 48 {
		err = ssz.ErrBytesLengthFn("Builder.Pubkey", size, 48)
		return
	}
	hh.PutBytes(b.Pubkey)

	// Field (1) 'Version'
	hh.PutUint8(b.Version)

	// Field (2) 'ExecutionAddress'
	hh.PutBytes(b.ExecutionAddress[:])

	// Field (3) 'Balance'
	hh.PutUint64(b.Balance)

	// Field (4) 'DepositEpoch'
	hh.PutUint64(b.DepositEpoch)

	// Field (5) 'WithdrawableEpoch'
	hh.PutUint64(b.WithdrawableEpoch)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Builder object
func (b *Builder) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the BuilderPendingWithdrawal object
func (b *BuilderPendingWithdrawal) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPendingWithdrawal object to a target array
func (b *BuilderPendingWithdrawal) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'FeeRecipient'
	dst = append(dst, b.FeeRecipient[:]...)

	// Field (1) 'Amount'
	dst = ssz.MarshalUint64(dst, b.Amount)

	// Field (2) 'BuilderIndex'
	dst = ssz.MarshalUint64(dst, b.BuilderIndex)

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPendingWithdrawal object
func (b *BuilderPendingWithdrawal) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 36 {
		return ssz.ErrSize
	}

	// Field (0) 'FeeRecipient'
	copy(b.FeeRecipient[:], buf[0:20])

	// Field (1) 'Amount'
	b.Amount = ssz.UnmarshallUint64(buf[20:28])

	// Field (2) 'BuilderIndex'
	b.BuilderIndex = ssz.UnmarshallUint64(buf[28:36])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPendingWithdrawal object
func (b *BuilderPendingWithdrawal) SizeSSZ() (size int) {
	size = 36
	return
}

// HashTreeRoot ssz hashes the BuilderPendingWithdrawal object
func (b *BuilderPendingWithdrawal) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPendingWithdrawal object with a hasher
func (b *BuilderPendingWithdrawal) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'FeeRecipient'
	hh.PutBytes(b.FeeRecipient[:])

	// Field (1) 'Amount'
	hh.PutUint64(b.Amount)

	// Field (2) 'BuilderIndex'
	hh.PutUint64(b.BuilderIndex)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BuilderPendingWithdrawal object
func (b *BuilderPendingWithdrawal) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the BuilderPendingPayment object
func (b *BuilderPendingPayment) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BuilderPendingPayment object to a target array
func (b *BuilderPendingPayment) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Weight'
	dst = ssz.MarshalUint64(dst, b.Weight)

	// Field (1) 'Withdrawal'
	if b.Withdrawal == nil {
		b.Withdrawal = new(BuilderPendingWithdrawal)
	}
	if dst, err = b.Withdrawal.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (2) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, b.ProposerIndex)

	return
}

// UnmarshalSSZ ssz unmarshals the BuilderPendingPayment object
func (b *BuilderPendingPayment) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 52 {
		return ssz.ErrSize
	}

	// Field (0) 'Weight'
	b.Weight = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Withdrawal'
	if b.Withdrawal == nil {
		b.Withdrawal = new(BuilderPendingWithdrawal)
	}
	if err = b.Withdrawal.UnmarshalSSZ(buf[8:44]); err != nil {
		return err
	}

	// Field (2) 'ProposerIndex'
	b.ProposerIndex = ssz.UnmarshallUint64(buf[44:52])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BuilderPendingPayment object
func (b *BuilderPendingPayment) SizeSSZ() (size int) {
	size = 52
	return
}

// HashTreeRoot ssz hashes the BuilderPendingPayment object
func (b *BuilderPendingPayment) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BuilderPendingPayment object with a hasher
func (b *BuilderPendingPayment) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Weight'
	hh.PutUint64(b.Weight)

	// Field (1) 'Withdrawal'
	if b.Withdrawal == nil {
		b.Withdrawal = new(BuilderPendingWithdrawal)
	}
	if err = b.Withdrawal.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (2) 'ProposerIndex'
	hh.PutUint64(b.ProposerIndex)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BuilderPendingPayment object
func (b *BuilderPendingPayment) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}

// MarshalSSZ ssz marshals the BeaconState object
func (b *BeaconState) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconState object to a target array
func (b *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(3134845)

	// Field (0) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, b.GenesisTime)

	// Field (1) 'GenesisValidatorsRoot'
	if size := len(b.GenesisValidatorsRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("BeaconState.GenesisValidatorsRoot", size, 32)
		return
	}
	dst = append(dst, b.GenesisValidatorsRoot...)

	// Field (2) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(generic.Fork)
	}
	if dst, err = b.Fork.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(generic.BeaconBlockHeader)
	}
	if dst, err = b.LatestBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (5) 'BlockRoots'
	for ii := 0; ii < 8192; ii++ {
		dst = append(dst, b.BlockRoots[ii][:]...)
	}

	// Field (6) 'StateRoots'
	for ii := 0; ii < 8192; ii++ {
		dst = append(dst, b.StateRoots[ii][:]...)
	}

	// Offset (7) 'HistoricalRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.HistoricalRoots) * 32

	// Field (8) 'Eth1Data'
	if b.Eth1Data == nil {
		b.Eth1Data = new(generic.Eth1Data)
	}
	if dst, err = b.Eth1Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (9) 'Eth1DataVotes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Eth1DataVotes) * 72

	// Field (10) 'Eth1DepositIndex'
	dst = ssz.MarshalUint64(dst, b.Eth1DepositIndex)

	// Offset (11) 'Validators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Validators) * 121

	// Offset (12) 'Balances'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Balances) * 8

	// Field (13) 'RandaoMixes'
	if size := len(b.RandaoMixes); size != 65536 {
		err = ssz.ErrVectorLengthFn("BeaconState.RandaoMixes", size, 65536)
		return
	}
	for ii := 0; ii < 65536; ii++ {
		if size := len(b.RandaoMixes[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("BeaconState.RandaoMixes[ii]", size, 32)
			return
		}
		dst = append(dst, b.RandaoMixes[ii]...)
	}

	// Field (14) 'Slashings'
	if size := len(b.Slashings); size != 8192 {
		err = ssz.ErrVectorLengthFn("BeaconState.Slashings", size, 8192)
		return
	}
	for ii := 0; ii < 8192; ii++ {
		dst = ssz.MarshalUint64(dst, b.Slashings[ii])
	}

	// Offset (15) 'PreviousEpochParticipation'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PreviousEpochParticipation)

	// Offset (16) 'CurrentEpochParticipation'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.CurrentEpochParticipation)

	// Field (17) 'JustificationBits'
	dst = append(dst, b.JustificationBits[:]...)

	// Field (18) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if dst, err = b.PreviousJustifiedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if dst, err = b.CurrentJustifiedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (20) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(generic.Checkpoint)
	}
	if dst, err = b.FinalizedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (21) 'InactivityScores'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.InactivityScores) * 8

	// Field (22) 'CurrentSyncCommittee'
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(generic.SyncCommittee)
	}
	if dst, err = b.CurrentSyncCommittee.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (23) 'NextSyncCommittee'
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(generic.SyncCommittee)
	}
	if dst, err = b.NextSyncCommittee.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (24) 'LatestBlockHash'
	dst = append(dst, b.LatestBlockHash[:]...)

	// Field (25) 'NextWithdrawalIndex'
	dst = ssz.MarshalUint64(dst, b.NextWithdrawalIndex)

	// Field (26) 'NextWithdrawalValidatorIndex'
	dst = ssz.MarshalUint64(dst, b.NextWithdrawalValidatorIndex)

	// Offset (27) 'HistoricalSummaries'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.HistoricalSummaries) * 64

	// Field (28) 'DepositRequestsStartIndex'
	dst = ssz.MarshalUint64(dst, b.DepositRequestsStartIndex)

	// Field (29) 'DepositBalanceToConsume'
	dst = ssz.MarshalUint64(dst, b.DepositBalanceToConsume)

	// Field (30) 'ExitBalanceToConsume'
	dst = ssz.MarshalUint64(dst, b.ExitBalanceToConsume)

	// Field (31) 'EarliestExitEpoch'
	dst = ssz.MarshalUint64(dst, b.EarliestExitEpoch)

	// Field (32) 'ConsolidationBalanceToConsume'
	dst = ssz.MarshalUint64(dst, b.ConsolidationBalanceToConsume)

	// Field (33) 'EarliestConsolidationEpoch'
	dst = ssz.MarshalUint64(dst, b.EarliestConsolidationEpoch)

	// Offset (34) 'PendingDeposits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingDeposits) * 192

	// Offset (35) 'PendingPartialWithdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingPartialWithdrawals) * 24

	// Offset (36) 'PendingConsolidations'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingConsolidations) * 16

	// Field (37) 'ProposerLookahead'
	if size := len(b.ProposerLookahead); size != 64 {
		err = ssz.ErrVectorLengthFn("BeaconState.ProposerLookahead", size, 64)
		return
	}
	for ii := 0; ii < 64; ii++ {
		dst = ssz.MarshalUint64(dst, b.ProposerLookahead[ii])
	}

	// Offset (38) 'Builders'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Builders) * 93

	// Field (39) 'NextWithdrawalBuilderIndex'
	dst = ssz.MarshalUint64(dst, b.NextWithdrawalBuilderIndex)

	// Field (40) 'ExecutionPayloadAvailability'
	if size := len(b.ExecutionPayloadAvailability); size != 1024 {
		err = ssz.ErrBytesLengthFn("BeaconState.ExecutionPayloadAvailability", size, 1024)
		return
	}
	dst = append(dst, b.ExecutionPayloadAvailability...)

	// Field (41) 'BuilderPendingPayments'
	if size := len(b.BuilderPendingPayments); size != 64 {
		err = ssz.ErrVectorLengthFn("BeaconState.BuilderPendingPayments", size, 64)
		return
	}
	for ii := 0; ii < 64; ii++ {
		if size := len(b.BuilderPendingPayments[ii]); size != 52 {
			err = ssz.ErrBytesLengthFn("BeaconState.BuilderPendingPayments[ii]", size, 52)
			return
		}
		dst = append(dst, b.BuilderPendingPayments[ii]...)
	}

	// Offset (42) 'BuilderPendingWithdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.BuilderPendingWithdrawals) * 36

	// Offset (43) 'LatestExecutionPayloadBid'
	dst = ssz.WriteOffset(dst, offset)
	if b.LatestExecutionPayloadBid == nil {
		b.LatestExecutionPayloadBid = new(ExecutionPayloadBid)
	}
	offset += b.LatestExecutionPayloadBid.SizeSSZ()

	// Offset (44) 'PayloadExpectedWithdrawals'
	dst = ssz.WriteOffset(dst, offset)

	// Field (45) 'PtcWindow'
	if size := len(b.PtcWindow); size != 49152 {
		err = ssz.ErrVectorLengthFn("BeaconState.PtcWindow", size, 49152)
		return
	}
	for ii := 0; ii < 49152; ii++ {
		dst = ssz.MarshalUint64(dst, b.PtcWindow[ii])
	}

	// Field (7) 'HistoricalRoots'
	if size := len(b.HistoricalRoots); size > 16777216 {
		err = ssz.ErrListTooBigFn("BeaconState.HistoricalRoots", size, 16777216)
		return
	}
	for ii := 0; ii < len(b.HistoricalRoots); ii++ {
		if size := len(b.HistoricalRoots[ii]); size != 32 {
			err = ssz.ErrBytesLengthFn("BeaconState.HistoricalRoots[ii]", size, 32)
			return
		}
		dst = append(dst, b.HistoricalRoots[ii]...)
	}

	// Field (9) 'Eth1DataVotes'
	if size := len(b.Eth1DataVotes); size > 2048 {
		err = ssz.ErrListTooBigFn("BeaconState.Eth1DataVotes", size, 2048)
		return
	}
	for ii := 0; ii < len(b.Eth1DataVotes); ii++ {
		if dst, err = b.Eth1DataVotes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (11) 'Validators'
	if size := len(b.Validators); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.Validators", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.Validators); ii++ {
		if dst, err = b.Validators[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (12) 'Balances'
	if size := len(b.Balances); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.Balances", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.Balances); ii++ {
		dst = ssz.MarshalUint64(dst, b.Balances[ii])
	}

	// Field (15) 'PreviousEpochParticipation'
	if size := len(b.PreviousEpochParticipation); size > 1099511627776 {
		err = ssz.ErrBytesLengthFn("BeaconState.PreviousEpochParticipation", size, 1099511627776)
		return
	}
	dst = append(dst, b.PreviousEpochParticipation...)

	// Field (16) 'CurrentEpochParticipation'
	if size := len(b.CurrentEpochParticipation); size > 1099511627776 {
		err = ssz.ErrBytesLengthFn("BeaconState.CurrentEpochParticipation", size, 1099511627776)
		return
	}
	dst = append(dst, b.CurrentEpochParticipation...)

	// Field (21) 'InactivityScores'
	if size := len(b.InactivityScores); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.InactivityScores", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.InactivityScores); ii++ {
		dst = ssz.MarshalUint64(dst, b.InactivityScores[ii])
	}

	// Field (27) 'HistoricalSummaries'
	if size := len(b.HistoricalSummaries); size > 16777216 {
		err = ssz.ErrListTooBigFn("BeaconState.HistoricalSummaries", size, 16777216)
		return
	}
	for ii := 0; ii < len(b.HistoricalSummaries); ii++ {
		if dst, err = b.HistoricalSummaries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (34) 'PendingDeposits'
	if size := len(b.PendingDeposits); size > 134217728 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingDeposits", size, 134217728)
		return
	}
	for ii := 0; ii < len(b.PendingDeposits); ii++ {
		if dst, err = b.PendingDeposits[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (35) 'PendingPartialWithdrawals'
	if size := len(b.PendingPartialWithdrawals); size > 134217728 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingPartialWithdrawals", size, 134217728)
		return
	}
	for ii := 0; ii < len(b.PendingPartialWithdrawals); ii++ {
		if dst, err = b.PendingPartialWithdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (36) 'PendingConsolidations'
	if size := len(b.PendingConsolidations); size > 262144 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingConsolidations", size, 262144)
		return
	}
	for ii := 0; ii < len(b.PendingConsolidations); ii++ {
		if dst, err = b.PendingConsolidations[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (38) 'Builders'
	if size := len(b.Builders); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.Builders", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.Builders); ii++ {
		if dst, err = b.Builders[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (42) 'BuilderPendingWithdrawals'
	if size := len(b.BuilderPendingWithdrawals); size > 134217728 {
		err = ssz.ErrListTooBigFn("BeaconState.BuilderPendingWithdrawals", size, 134217728)
		return
	}
	for ii := 0; ii < len(b.BuilderPendingWithdrawals); ii++ {
		if dst, err = b.BuilderPendingWithdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (43) 'LatestExecutionPayloadBid'
	if dst, err = b.LatestExecutionPayloadBid.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (44) 'PayloadExpectedWithdrawals'
	if size := len(b.PayloadExpectedWithdrawals); size > 16 {
		err = ssz.ErrListTooBigFn("BeaconState.PayloadExpectedWithdrawals", size, 16)
		return
	}
	for ii := 0; ii < len(b.PayloadExpectedWithdrawals); ii++ {
		if dst, err = b.PayloadExpectedWithdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconState object
func (b *BeaconState) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 3134845 {
		return ssz.ErrSize
	}

	tail := buf
	var o7, o9, o11, o12, o15, o16, o21, o27, o34, o35, o36, o38, o42, o43, o44 uint64

	// Field (0) 'GenesisTime'
	b.GenesisTime = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'GenesisValidatorsRoot'
	if cap(b.GenesisValidatorsRoot) == 0 {
		b.GenesisValidatorsRoot = make([]byte, 0, len(buf[8:40]))
	}
	b.GenesisValidatorsRoot = append(b.GenesisValidatorsRoot, buf[8:40]...)

	// Field (2) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[40:48])

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(generic.Fork)
	}
	if err = b.Fork.UnmarshalSSZ(buf[48:64]); err != nil {
		return err
	}

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(generic.BeaconBlockHeader)
	}
	if err = b.LatestBlockHeader.UnmarshalSSZ(buf[64:176]); err != nil {
		return err
	}

	// Field (5) 'BlockRoots'

	for ii := 0; ii < 8192; ii++ {
		copy(b.BlockRoots[ii][:], buf[176:262320][ii*32:(ii+1)*32])
	}

	// Field (6) 'StateRoots'

	for ii := 0; ii < 8192; ii++ {
		copy(b.StateRoots[ii][:], buf[262320:524464][ii*32:(ii+1)*32])
	}

	// Offset (7) 'HistoricalRoots'
	if o7 = ssz.ReadOffset(buf[524464:524468]); o7 > size {
		return ssz.ErrOffset
	}

	if o7 != 3134845 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (8) 'Eth1Data'
	if b.Eth1Data == nil {
		b.Eth1Data = new(generic.Eth1Data)
	}
	if err = b.Eth1Data.UnmarshalSSZ(buf[524468:524540]); err != nil {
		return err
	}

	// Offset (9) 'Eth1DataVotes'
	if o9 = ssz.ReadOffset(buf[524540:524544]); o9 > size || o7 > o9 {
		return ssz.ErrOffset
	}

	// Field (10) 'Eth1DepositIndex'
	b.Eth1DepositIndex = ssz.UnmarshallUint64(buf[524544:524552])

	// Offset (11) 'Validators'
	if o11 = ssz.ReadOffset(buf[524552:524556]); o11 > size || o9 > o11 {
		return ssz.ErrOffset
	}

	// Offset (12) 'Balances'
	if o12 = ssz.ReadOffset(buf[524556:524560]); o12 > size || o11 > o12 {
		return ssz.ErrOffset
	}

	// Field (13) 'RandaoMixes'
	b.RandaoMixes = make([][]byte, 65536)
	for ii := 0; ii < 65536; ii++ {
		if cap(b.RandaoMixes[ii]) == 0 {
			b.RandaoMixes[ii] = make([]byte, 0, len(buf[524560:2621712][ii*32:(ii+1)*32]))
		}
		b.RandaoMixes[ii] = append(b.RandaoMixes[ii], buf[524560:2621712][ii*32:(ii+1)*32]...)
	}

	// Field (14) 'Slashings'
	b.Slashings = ssz.ExtendUint64(b.Slashings, 8192)
	for ii := 0; ii < 8192; ii++ {
		b.Slashings[ii] = ssz.UnmarshallUint64(buf[2621712:2687248][ii*8 : (ii+1)*8])
	}

	// Offset (15) 'PreviousEpochParticipation'
	if o15 = ssz.ReadOffset(buf[2687248:2687252]); o15 > size || o12 > o15 {
		return ssz.ErrOffset
	}

	// Offset (16) 'CurrentEpochParticipation'
	if o16 = ssz.ReadOffset(buf[2687252:2687256]); o16 > size || o15 > o16 {
		return ssz.ErrOffset
	}

	// Field (17) 'JustificationBits'
	copy(b.JustificationBits[:], buf[2687256:2687257])

	// Field (18) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf[2687257:2687297]); err != nil {
		return err
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf[2687297:2687337]); err != nil {
		return err
	}

	// Field (20) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.FinalizedCheckpoint.UnmarshalSSZ(buf[2687337:2687377]); err != nil {
		return err
	}

	// Offset (21) 'InactivityScores'
	if o21 = ssz.ReadOffset(buf[2687377:2687381]); o21 > size || o16 > o21 {
		return ssz.ErrOffset
	}

	// Field (22) 'CurrentSyncCommittee'
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(generic.SyncCommittee)
	}
	if err = b.CurrentSyncCommittee.UnmarshalSSZ(buf[2687381:2712005]); err != nil {
		return err
	}

	// Field (23) 'NextSyncCommittee'
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(generic.SyncCommittee)
	}
	if err = b.NextSyncCommittee.UnmarshalSSZ(buf[2712005:2736629]); err != nil {
		return err
	}

	// Field (24) 'LatestBlockHash'
	copy(b.LatestBlockHash[:], buf[2736629:2736661])

	// Field (25) 'NextWithdrawalIndex'
	b.NextWithdrawalIndex = ssz.UnmarshallUint64(buf[2736661:2736669])

	// Field (26) 'NextWithdrawalValidatorIndex'
	b.NextWithdrawalValidatorIndex = ssz.UnmarshallUint64(buf[2736669:2736677])

	// Offset (27) 'HistoricalSummaries'
	if o27 = ssz.ReadOffset(buf[2736677:2736681]); o27 > size || o21 > o27 {
		return ssz.ErrOffset
	}

	// Field (28) 'DepositRequestsStartIndex'
	b.DepositRequestsStartIndex = ssz.UnmarshallUint64(buf[2736681:2736689])

	// Field (29) 'DepositBalanceToConsume'
	b.DepositBalanceToConsume = ssz.UnmarshallUint64(buf[2736689:2736697])

	// Field (30) 'ExitBalanceToConsume'
	b.ExitBalanceToConsume = ssz.UnmarshallUint64(buf[2736697:2736705])

	// Field (31) 'EarliestExitEpoch'
	b.EarliestExitEpoch = ssz.UnmarshallUint64(buf[2736705:2736713])

	// Field (32) 'ConsolidationBalanceToConsume'
	b.ConsolidationBalanceToConsume = ssz.UnmarshallUint64(buf[2736713:2736721])

	// Field (33) 'EarliestConsolidationEpoch'
	b.EarliestConsolidationEpoch = ssz.UnmarshallUint64(buf[2736721:2736729])

	// Offset (34) 'PendingDeposits'
	if o34 = ssz.ReadOffset(buf[2736729:2736733]); o34 > size || o27 > o34 {
		return ssz.ErrOffset
	}

	// Offset (35) 'PendingPartialWithdrawals'
	if o35 = ssz.ReadOffset(buf[2736733:2736737]); o35 > size || o34 > o35 {
		return ssz.ErrOffset
	}

	// Offset (36) 'PendingConsolidations'
	if o36 = ssz.ReadOffset(buf[2736737:2736741]); o36 > size || o35 > o36 {
		return ssz.ErrOffset
	}

	// Field (37) 'ProposerLookahead'
	b.ProposerLookahead = ssz.ExtendUint64(b.ProposerLookahead, 64)
	for ii := 0; ii < 64; ii++ {
		b.ProposerLookahead[ii] = ssz.UnmarshallUint64(buf[2736741:2737253][ii*8 : (ii+1)*8])
	}

	// Offset (38) 'Builders'
	if o38 = ssz.ReadOffset(buf[2737253:2737257]); o38 > size || o36 > o38 {
		return ssz.ErrOffset
	}

	// Field (39) 'NextWithdrawalBuilderIndex'
	b.NextWithdrawalBuilderIndex = ssz.UnmarshallUint64(buf[2737257:2737265])

	// Field (40) 'ExecutionPayloadAvailability'
	if cap(b.ExecutionPayloadAvailability) == 0 {
		b.ExecutionPayloadAvailability = make([]byte, 0, len(buf[2737265:2738289]))
	}
	b.ExecutionPayloadAvailability = append(b.ExecutionPayloadAvailability, buf[2737265:2738289]...)

	// Field (41) 'BuilderPendingPayments'
	b.BuilderPendingPayments = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		if cap(b.BuilderPendingPayments[ii]) == 0 {
			b.BuilderPendingPayments[ii] = make([]byte, 0, len(buf[2738289:2741617][ii*52:(ii+1)*52]))
		}
		b.BuilderPendingPayments[ii] = append(b.BuilderPendingPayments[ii], buf[2738289:2741617][ii*52:(ii+1)*52]...)
	}

	// Offset (42) 'BuilderPendingWithdrawals'
	if o42 = ssz.ReadOffset(buf[2741617:2741621]); o42 > size || o38 > o42 {
		return ssz.ErrOffset
	}

	// Offset (43) 'LatestExecutionPayloadBid'
	if o43 = ssz.ReadOffset(buf[2741621:2741625]); o43 > size || o42 > o43 {
		return ssz.ErrOffset
	}

	// Offset (44) 'PayloadExpectedWithdrawals'
	if o44 = ssz.ReadOffset(buf[2741625:2741629]); o44 > size || o43 > o44 {
		return ssz.ErrOffset
	}

	// Field (45) 'PtcWindow'
	b.PtcWindow = ssz.ExtendUint64(b.PtcWindow, 49152)
	for ii := 0; ii < 49152; ii++ {
		b.PtcWindow[ii] = ssz.UnmarshallUint64(buf[2741629:3134845][ii*8 : (ii+1)*8])
	}

	// Field (7) 'HistoricalRoots'
	{
		buf = tail[o7:o9]
		num, err := ssz.DivideInt2(len(buf), 32, 16777216)
		if err != nil {
			return err
		}
		b.HistoricalRoots = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(b.HistoricalRoots[ii]) == 0 {
				b.HistoricalRoots[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			b.HistoricalRoots[ii] = append(b.HistoricalRoots[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (9) 'Eth1DataVotes'
	{
		buf = tail[o9:o11]
		num, err := ssz.DivideInt2(len(buf), 72, 2048)
		if err != nil {
			return err
		}
		b.Eth1DataVotes = make([]*generic.Eth1Data, num)
		for ii := 0; ii < num; ii++ {
			if b.Eth1DataVotes[ii] == nil {
				b.Eth1DataVotes[ii] = new(generic.Eth1Data)
			}
			if err = b.Eth1DataVotes[ii].UnmarshalSSZ(buf[ii*72 : (ii+1)*72]); err != nil {
				return err
			}
		}
	}

	// Field (11) 'Validators'
	{
		buf = tail[o11:o12]
		num, err := ssz.DivideInt2(len(buf), 121, 1099511627776)
		if err != nil {
			return err
		}
		b.Validators = make([]*generic.Validator, num)
		for ii := 0; ii < num; ii++ {
			if b.Validators[ii] == nil {
				b.Validators[ii] = new(generic.Validator)
			}
			if err = b.Validators[ii].UnmarshalSSZ(buf[ii*121 : (ii+1)*121]); err != nil {
				return err
			}
		}
	}

	// Field (12) 'Balances'
	{
		buf = tail[o12:o15]
		num, err := ssz.DivideInt2(len(buf), 8, 1099511627776)
		if err != nil {
			return err
		}
		b.Balances = ssz.ExtendUint64(b.Balances, num)
		for ii := 0; ii < num; ii++ {
			b.Balances[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (15) 'PreviousEpochParticipation'
	{
		buf = tail[o15:o16]
		if len(buf) > 1099511627776 {
			return ssz.ErrBytesLength
		}
		if cap(b.PreviousEpochParticipation) == 0 {
			b.PreviousEpochParticipation = make([]byte, 0, len(buf))
		}
		b.PreviousEpochParticipation = append(b.PreviousEpochParticipation, buf...)
	}

	// Field (16) 'CurrentEpochParticipation'
	{
		buf = tail[o16:o21]
		if len(buf) > 1099511627776 {
			return ssz.ErrBytesLength
		}
		if cap(b.CurrentEpochParticipation) == 0 {
			b.CurrentEpochParticipation = make([]byte, 0, len(buf))
		}
		b.CurrentEpochParticipation = append(b.CurrentEpochParticipation, buf...)
	}

	// Field (21) 'InactivityScores'
	{
		buf = tail[o21:o27]
		num, err := ssz.DivideInt2(len(buf), 8, 1099511627776)
		if err != nil {
			return err
		}
		b.InactivityScores = ssz.ExtendUint64(b.InactivityScores, num)
		for ii := 0; ii < num; ii++ {
			b.InactivityScores[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (27) 'HistoricalSummaries'
	{
		buf = tail[o27:o34]
		num, err := ssz.DivideInt2(len(buf), 64, 16777216)
		if err != nil {
			return err
		}
		b.HistoricalSummaries = make([]*generic.HistoricalSummary, num)
		for ii := 0; ii < num; ii++ {
			if b.HistoricalSummaries[ii] == nil {
				b.HistoricalSummaries[ii] = new(generic.HistoricalSummary)
			}
			if err = b.HistoricalSummaries[ii].UnmarshalSSZ(buf[ii*64 : (ii+1)*64]); err != nil {
				return err
			}
		}
	}

	// Field (34) 'PendingDeposits'
	{
		buf = tail[o34:o35]
		num, err := ssz.DivideInt2(len(buf), 192, 134217728)
		if err != nil {
			return err
		}
		b.PendingDeposits = make([]*generic.PendingDeposit, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingDeposits[ii] == nil {
				b.PendingDeposits[ii] = new(generic.PendingDeposit)
			}
			if err = b.PendingDeposits[ii].UnmarshalSSZ(buf[ii*192 : (ii+1)*192]); err != nil {
				return err
			}
		}
	}

	// Field (35) 'PendingPartialWithdrawals'
	{
		buf = tail[o35:o36]
		num, err := ssz.DivideInt2(len(buf), 24, 134217728)
		if err != nil {
			return err
		}
		b.PendingPartialWithdrawals = make([]*generic.PendingPartialWithdrawal, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingPartialWithdrawals[ii] == nil {
				b.PendingPartialWithdrawals[ii] = new(generic.PendingPartialWithdrawal)
			}
			if err = b.PendingPartialWithdrawals[ii].UnmarshalSSZ(buf[ii*24 : (ii+1)*24]); err != nil {
				return err
			}
		}
	}

	// Field (36) 'PendingConsolidations'
	{
		buf = tail[o36:o38]
		num, err := ssz.DivideInt2(len(buf), 16, 262144)
		if err != nil {
			return err
		}
		b.PendingConsolidations = make([]*generic.PendingConsolidation, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingConsolidations[ii] == nil {
				b.PendingConsolidations[ii] = new(generic.PendingConsolidation)
			}
			if err = b.PendingConsolidations[ii].UnmarshalSSZ(buf[ii*16 : (ii+1)*16]); err != nil {
				return err
			}
		}
	}

	// Field (38) 'Builders'
	{
		buf = tail[o38:o42]
		num, err := ssz.DivideInt2(len(buf), 93, 1099511627776)
		if err != nil {
			return err
		}
		b.Builders = make([]*Builder, num)
		for ii := 0; ii < num; ii++ {
			if b.Builders[ii] == nil {
				b.Builders[ii] = new(Builder)
			}
			if err = b.Builders[ii].UnmarshalSSZ(buf[ii*93 : (ii+1)*93]); err != nil {
				return err
			}
		}
	}

	// Field (42) 'BuilderPendingWithdrawals'
	{
		buf = tail[o42:o43]
		num, err := ssz.DivideInt2(len(buf), 36, 134217728)
		if err != nil {
			return err
		}
		b.BuilderPendingWithdrawals = make([]*BuilderPendingWithdrawal, num)
		for ii := 0; ii < num; ii++ {
			if b.BuilderPendingWithdrawals[ii] == nil {
				b.BuilderPendingWithdrawals[ii] = new(BuilderPendingWithdrawal)
			}
			if err = b.BuilderPendingWithdrawals[ii].UnmarshalSSZ(buf[ii*36 : (ii+1)*36]); err != nil {
				return err
			}
		}
	}

	// Field (43) 'LatestExecutionPayloadBid'
	{
		buf = tail[o43:o44]
		if b.LatestExecutionPayloadBid == nil {
			b.LatestExecutionPayloadBid = new(ExecutionPayloadBid)
		}
		if err = b.LatestExecutionPayloadBid.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (44) 'PayloadExpectedWithdrawals'
	{
		buf = tail[o44:]
		num, err := ssz.DivideInt2(len(buf), 44, 16)
		if err != nil {
			return err
		}
		b.PayloadExpectedWithdrawals = make([]*generic.Withdrawal, num)
		for ii := 0; ii < num; ii++ {
			if b.PayloadExpectedWithdrawals[ii] == nil {
				b.PayloadExpectedWithdrawals[ii] = new(generic.Withdrawal)
			}
			if err = b.PayloadExpectedWithdrawals[ii].UnmarshalSSZ(buf[ii*44 : (ii+1)*44]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconState object
func (b *BeaconState) SizeSSZ() (size int) {
	size = 3134845

	// Field (7) 'HistoricalRoots'
	size += len(b.HistoricalRoots) * 32

	// Field (9) 'Eth1DataVotes'
	size += len(b.Eth1DataVotes) * 72

	// Field (11) 'Validators'
	size += len(b.Validators) * 121

	// Field (12) 'Balances'
	size += len(b.Balances) * 8

	// Field (15) 'PreviousEpochParticipation'
	size += len(b.PreviousEpochParticipation)

	// Field (16) 'CurrentEpochParticipation'
	size += len(b.CurrentEpochParticipation)

	// Field (21) 'InactivityScores'
	size += len(b.InactivityScores) * 8

	// Field (27) 'HistoricalSummaries'
	size += len(b.HistoricalSummaries) * 64

	// Field (34) 'PendingDeposits'
	size += len(b.PendingDeposits) * 192

	// Field (35) 'PendingPartialWithdrawals'
	size += len(b.PendingPartialWithdrawals) * 24

	// Field (36) 'PendingConsolidations'
	size += len(b.PendingConsolidations) * 16

	// Field (38) 'Builders'
	size += len(b.Builders) * 93

	// Field (42) 'BuilderPendingWithdrawals'
	size += len(b.BuilderPendingWithdrawals) * 36

	// Field (43) 'LatestExecutionPayloadBid'
	if b.LatestExecutionPayloadBid == nil {
		b.LatestExecutionPayloadBid = new(ExecutionPayloadBid)
	}
	size += b.LatestExecutionPayloadBid.SizeSSZ()

	// Field (44) 'PayloadExpectedWithdrawals'
	size += len(b.PayloadExpectedWithdrawals) * 44

	return
}

// HashTreeRoot ssz hashes the BeaconState object
func (b *BeaconState) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconState object with a hasher
func (b *BeaconState) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'GenesisTime'
	hh.PutUint64(b.GenesisTime)

	// Field (1) 'GenesisValidatorsRoot'
	if size := len(b.GenesisValidatorsRoot); size != 32 {
		err = ssz.ErrBytesLengthFn("BeaconState.GenesisValidatorsRoot", size, 32)
		return
	}
	hh.PutBytes(b.GenesisValidatorsRoot)

	// Field (2) 'Slot'
	hh.PutUint64(b.Slot)

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(generic.Fork)
	}
	if err = b.Fork.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(generic.BeaconBlockHeader)
	}
	if err = b.LatestBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'BlockRoots'
	{
		subIndx := hh.Index()
		for _, i := range b.BlockRoots {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	// Field (6) 'StateRoots'
	{
		subIndx := hh.Index()
		for _, i := range b.StateRoots {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	// Field (7) 'HistoricalRoots'
	{
		if size := len(b.HistoricalRoots); size > 16777216 {
			err = ssz.ErrListTooBigFn("BeaconState.HistoricalRoots", size, 16777216)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.HistoricalRoots {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}
		numItems := uint64(len(b.HistoricalRoots))
		hh.MerkleizeWithMixin(subIndx, numItems, 16777216)
	}

	// Field (8) 'Eth1Data'
	if b.Eth1Data == nil {
		b.Eth1Data = new(generic.Eth1Data)
	}
	if err = b.Eth1Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (9) 'Eth1DataVotes'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Eth1DataVotes))
		if num > 2048 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Eth1DataVotes {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 2048)
	}

	// Field (10) 'Eth1DepositIndex'
	hh.PutUint64(b.Eth1DepositIndex)

	// Field (11) 'Validators'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Validators))
		if num > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Validators {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1099511627776)
	}

	// Field (12) 'Balances'
	{
		if size := len(b.Balances); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.Balances", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.Balances {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.Balances))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 8))
	}

	// Field (13) 'RandaoMixes'
	{
		if size := len(b.RandaoMixes); size != 65536 {
			err = ssz.ErrVectorLengthFn("BeaconState.RandaoMixes", size, 65536)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.RandaoMixes {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}
		hh.Merkleize(subIndx)
	}

	// Field (14) 'Slashings'
	{
		if size := len(b.Slashings); size != 8192 {
			err = ssz.ErrVectorLengthFn("BeaconState.Slashings", size, 8192)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.Slashings {
			hh.AppendUint64(i)
		}
		hh.Merkleize(subIndx)
	}

	// Field (15) 'PreviousEpochParticipation'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(b.PreviousEpochParticipation))
		if byteLen > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(b.PreviousEpochParticipation)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1099511627776+31)/32)
	}

	// Field (16) 'CurrentEpochParticipation'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(b.CurrentEpochParticipation))
		if byteLen > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(b.CurrentEpochParticipation)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (1099511627776+31)/32)
	}

	// Field (17) 'JustificationBits'
	hh.PutBytes(b.JustificationBits[:])

	// Field (18) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.PreviousJustifiedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.CurrentJustifiedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (20) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(generic.Checkpoint)
	}
	if err = b.FinalizedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (21) 'InactivityScores'
	{
		if size := len(b.InactivityScores); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.InactivityScores", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.InactivityScores {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.InactivityScores))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 8))
	}

	// Field (22) 'CurrentSyncCommittee'
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(generic.SyncCommittee)
	}
	if err = b.CurrentSyncCommittee.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (23) 'NextSyncCommittee'
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(generic.SyncCommittee)
	}
	if err = b.NextSyncCommittee.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (24) 'LatestBlockHash'
	hh.PutBytes(b.LatestBlockHash[:])

	// Field (25) 'NextWithdrawalIndex'
	hh.PutUint64(b.NextWithdrawalIndex)

	// Field (26) 'NextWithdrawalValidatorIndex'
	hh.PutUint64(b.NextWithdrawalValidatorIndex)

	// Field (27) 'HistoricalSummaries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.HistoricalSummaries))
		if num > 16777216 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.HistoricalSummaries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16777216)
	}

	// Field (28) 'DepositRequestsStartIndex'
	hh.PutUint64(b.DepositRequestsStartIndex)

	// Field (29) 'DepositBalanceToConsume'
	hh.PutUint64(b.DepositBalanceToConsume)

	// Field (30) 'ExitBalanceToConsume'
	hh.PutUint64(b.ExitBalanceToConsume)

	// Field (31) 'EarliestExitEpoch'
	hh.PutUint64(b.EarliestExitEpoch)

	// Field (32) 'ConsolidationBalanceToConsume'
	hh.PutUint64(b.ConsolidationBalanceToConsume)

	// Field (33) 'EarliestConsolidationEpoch'
	hh.PutUint64(b.EarliestConsolidationEpoch)

	// Field (34) 'PendingDeposits'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingDeposits))
		if num > 134217728 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingDeposits {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 134217728)
	}

	// Field (35) 'PendingPartialWithdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingPartialWithdrawals))
		if num > 134217728 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingPartialWithdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 134217728)
	}

	// Field (36) 'PendingConsolidations'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingConsolidations))
		if num > 262144 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingConsolidations {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 262144)
	}

	// Field (37) 'ProposerLookahead'
	{
		if size := len(b.ProposerLookahead); size != 64 {
			err = ssz.ErrVectorLengthFn("BeaconState.ProposerLookahead", size, 64)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.ProposerLookahead {
			hh.AppendUint64(i)
		}
		hh.Merkleize(subIndx)
	}

	// Field (38) 'Builders'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Builders))
		if num > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Builders {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1099511627776)
	}

	// Field (39) 'NextWithdrawalBuilderIndex'
	hh.PutUint64(b.NextWithdrawalBuilderIndex)

	// Field (40) 'ExecutionPayloadAvailability'
	if size := len(b.ExecutionPayloadAvailability); size != 1024 {
		err = ssz.ErrBytesLengthFn("BeaconState.ExecutionPayloadAvailability", size, 1024)
		return
	}
	hh.PutBytes(b.ExecutionPayloadAvailability)

	// Field (41) 'BuilderPendingPayments'
	{
		if size := len(b.BuilderPendingPayments); size != 64 {
			err = ssz.ErrVectorLengthFn("BeaconState.BuilderPendingPayments", size, 64)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.BuilderPendingPayments {
			if len(i) != 52 {
				err = ssz.ErrBytesLength
				return
			}
			hh.PutBytes(i)
		}
		hh.Merkleize(subIndx)
	}

	// Field (42) 'BuilderPendingWithdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(b.BuilderPendingWithdrawals))
		if num > 134217728 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.BuilderPendingWithdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 134217728)
	}

	// Field (43) 'LatestExecutionPayloadBid'
	if err = b.LatestExecutionPayloadBid.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (44) 'PayloadExpectedWithdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PayloadExpectedWithdrawals))
		if num > 16 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PayloadExpectedWithdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16)
	}

	// Field (45) 'PtcWindow'
	{
		if size := len(b.PtcWindow); size != 49152 {
			err = ssz.ErrVectorLengthFn("BeaconState.PtcWindow", size, 49152)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.PtcWindow {
			hh.AppendUint64(i)
		}
		hh.Merkleize(subIndx)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BeaconState object
func (b *BeaconState) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
